// Generated by gencpp from file bot3_kccistc_service/bot3gpio.msg
// DO NOT EDIT!


#ifndef BOT3_KCCISTC_SERVICE_MESSAGE_BOT3GPIO_H
#define BOT3_KCCISTC_SERVICE_MESSAGE_BOT3GPIO_H

#include <ros/service_traits.h>


#include <bot3_kccistc_service/bot3gpioRequest.h>
#include <bot3_kccistc_service/bot3gpioResponse.h>


namespace bot3_kccistc_service
{

struct bot3gpio
{

typedef bot3gpioRequest Request;
typedef bot3gpioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct bot3gpio
} // namespace bot3_kccistc_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bot3_kccistc_service::bot3gpio > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::bot3_kccistc_service::bot3gpio&) { return value(); }
};

template<>
struct DataType< ::bot3_kccistc_service::bot3gpio > {
  static const char* value()
  {
    return "bot3_kccistc_service/bot3gpio";
  }

  static const char* value(const ::bot3_kccistc_service::bot3gpio&) { return value(); }
};


// service_traits::MD5Sum< ::bot3_kccistc_service::bot3gpioRequest> should match
// service_traits::MD5Sum< ::bot3_kccistc_service::bot3gpio >
template<>
struct MD5Sum< ::bot3_kccistc_service::bot3gpioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bot3_kccistc_service::bot3gpio >::value();
  }
  static const char* value(const ::bot3_kccistc_service::bot3gpioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bot3_kccistc_service::bot3gpioRequest> should match
// service_traits::DataType< ::bot3_kccistc_service::bot3gpio >
template<>
struct DataType< ::bot3_kccistc_service::bot3gpioRequest>
{
  static const char* value()
  {
    return DataType< ::bot3_kccistc_service::bot3gpio >::value();
  }
  static const char* value(const ::bot3_kccistc_service::bot3gpioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bot3_kccistc_service::bot3gpioResponse> should match
// service_traits::MD5Sum< ::bot3_kccistc_service::bot3gpio >
template<>
struct MD5Sum< ::bot3_kccistc_service::bot3gpioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bot3_kccistc_service::bot3gpio >::value();
  }
  static const char* value(const ::bot3_kccistc_service::bot3gpioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bot3_kccistc_service::bot3gpioResponse> should match
// service_traits::DataType< ::bot3_kccistc_service::bot3gpio >
template<>
struct DataType< ::bot3_kccistc_service::bot3gpioResponse>
{
  static const char* value()
  {
    return DataType< ::bot3_kccistc_service::bot3gpio >::value();
  }
  static const char* value(const ::bot3_kccistc_service::bot3gpioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOT3_KCCISTC_SERVICE_MESSAGE_BOT3GPIO_H
